### ISSUE TITLE
Improve intersect functions documentation

### ISSUE THREAD

**Issue by jbuckmccready** [jbuckmccready/cavalier_contours#10]
The functions in `circle_circle_intersect.rs`, `line_circle_intersect.rs`, `line_line_intersect.rs`, under `cavalier_contours/core/math` and `cavalier_contours/polyline/pline_seg_intersect.rs` need code examples added to their documentation. E.g. `circle_circle_intr` just has `/// Finds the intersects between two circles.`

Add more documentation about their parameters, and add a basic code example similar to what is done for the functions in the `cavalier_contours/polyline/pline_seg.rs` module.

**Comment by Nevsden** [comment]
Also wanted to mention, that the way you have written the macro `assert_case_eq` (e.g. for `line_line_intr`) in your testing suite is neat!

**Comment by jbuckmccready** [comment]
Improved with PR https://github.com/jbuckmccready/cavalier_contours/pull/18, thanks @Nevsden.
