### ISSUE TITLE
[Feat] transplant: polyline offset islands

### ISSUE THREAD

**Issue by FishOrBear** [jbuckmccready/cavalier_contours#14]
https://github.com/jbuckmccready/CavalierContours/blob/master/include/cavc/polylineoffsetislands.hpp

**Comment by jbuckmccready** [comment]
I'd like to tackle this with the generic shape type (issue https://github.com/jbuckmccready/cavalier_contours/issues/7).

**Comment by FishOrBear** [comment]
Looking forward to this
